=== camenduru/outpaint-flux-fill-tost/schema.json
{
  "$schema": "http://json-schema.org/draft-04/hyper-schema#",
  "type": "object",
  "properties": {
    "readme": {
      "type": "string",
      "title": "Model: Flux.1 Dev Fill",
      "author": "Black Forest Labs: Andreas Blattmann, Andrew Holmes, Axel Sauer, Dominik Lorenz, Dustin Podell, Frederic Boesel, Harry Saini, Jonas MÃ¼ller, Kyle Lacey, Patrick Esser, Robin Rombach, Sumith Kulal, Tim Dockhorn, Yam Levi, Zion English",
      "page": "https://blackforestlabs.ai/",
      "code": "https://github.com/black-forest-labs/flux",
      "jupyter": "https://github.com/camenduru/flux-jupyter",
      "api": "https://github.com/camenduru/tost-api-examples/blob/main/v1/outpaint-flux-fill.ipynb",
      "tags": [
        "Image to Image"
      ],
      "widget": "readme"
    },
    "upload": {
      "type": "string",
      "widget": "upload",
      "upload_url": "https://litterbox.catbox.moe/resources/internals/api.php",
      "property": "input_image"
    },
    "input_image": {
      "type": "string",
      "description": "Image URL",
      "widget": "textarea"
    },
    "left": {
      "type": "integer",
      "description": "Left"
    },
    "right": {
      "type": "integer",
      "description": "Right"
    },
    "top": {
      "type": "integer",
      "description": "Top"
    },
    "bottom": {
      "type": "integer",
      "description": "Bottom"
    },
    "feathering": {
      "type": "integer",
      "description": "Feathering"
    },
    "positive_prompt": {
      "type": "string",
      "description": "Positive Prompt",
      "widget": "textarea"
    },
    "negative_prompt": {
      "type": "string",
      "description": "Negative Prompt",
      "widget": "textarea"
    },
    "seed": {
      "type": "integer",
      "description": "Seed (if 0 random)"
    },
    "steps": {
      "type": "integer",
      "widget": "select",
      "description": "Steps",
      "oneOf": [
        {
          "description": "20",
          "enum": [
            20
          ]
        },
        {
          "description": "25",
          "enum": [
            25
          ]
        },
        {
          "description": "30",
          "enum": [
            30
          ]
        },
        {
          "description": "35",
          "enum": [
            35
          ]
        },
        {
          "description": "40",
          "enum": [
            40
          ]
        }
      ],
      "default": 20
    },
    "guidance": {
      "type": "number",
      "description": "Guidance"
    },
    "cfg": {
      "type": "number",
      "description": "CFG"
    },
    "sampler_name": {
      "type": "string",
      "widget": "select",
      "description": "Sampler Name",
      "oneOf": [
        {
          "description": "euler",
          "enum": [
            "euler"
          ]
        },
        {
          "description": "heun",
          "enum": [
            "heun"
          ]
        },
        {
          "description": "heunpp2",
          "enum": [
            "heunpp2"
          ]
        },
        {
          "description": "dpm_2",
          "enum": [
            "dpm_2"
          ]
        },
        {
          "description": "lms",
          "enum": [
            "lms"
          ]
        },
        {
          "description": "dpmpp_2m",
          "enum": [
            "dpmpp_2m"
          ]
        },
        {
          "description": "ipndm",
          "enum": [
            "ipndm"
          ]
        },
        {
          "description": "deis",
          "enum": [
            "deis"
          ]
        },
        {
          "description": "ddim",
          "enum": [
            "ddim"
          ]
        },
        {
          "description": "uni_pc",
          "enum": [
            "uni_pc"
          ]
        },
        {
          "description": "uni_pc_bh2",
          "enum": [
            "uni_pc_bh2"
          ]
        }
      ],
      "default": "euler"
    },
    "scheduler": {
      "type": "string",
      "widget": "select",
      "description": "Scheduler",
      "oneOf": [
        {
          "description": "beta",
          "enum": [
            "beta"
          ]
        },
        {
          "description": "normal",
          "enum": [
            "normal"
          ]
        },
        {
          "description": "sgm_uniform",
          "enum": [
            "sgm_uniform"
          ]
        },
        {
          "description": "simple",
          "enum": [
            "simple"
          ]
        },
        {
          "description": "ddim_uniform",
          "enum": [
            "ddim_uniform"
          ]
        }
      ],
      "default": "normal"
    },
    "example": {
      "type": "string",
      "image1": "https://fakeimg.pl/512x512/282828/eae0d0/?text=input#.png",
      "image2": "https://files.catbox.moe/pqi6yz.png",
      "image3": "https://fakeimg.pl/512x512/282828/eae0d0/?text=output#.png",
      "image4": "https://files.catbox.moe/erhf43.png",
      "widget": "example"
    }
  },
  "buttons": [
    {
      "id": "enter",
      "label": "ðŸ¥ª Enter"
    }
  ]
}

=== camenduru/outpaint-flux-fill-tost/model.json
{
    "input_image": "https://files.catbox.moe/pqi6yz.png",
    "left": 600,
    "right": 600,
    "top": 0,
    "bottom": 0,
    "feathering": 24,
    "positive_prompt": "high definition",
    "negative_prompt": "blurry",
    "seed": 0,
    "steps": 20,
    "guidance": 30,
    "cfg": 1.0,
    "sampler_name": "euler",
    "scheduler": "normal"
}
